### ISSUE TITLE
Open Preview on markdown files are not working 

### ISSUE THREAD

**Issue by tujeff** [gitpod-io/openvscode-server#268]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by tujeff** [comment]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: openvscode docker 1.63.0
OS Version: Debian bullseye
Steps to Reproduce:
1. Create a simple md file
2. A blank screen shown when open preview

**Comment by jeanp413** [comment]
@tujeff I cannot reproduce, I tested in chrome and firefox, what browser are you using? do you see a relevant error in dev tools console?

**Comment by tujeff** [comment]
I'm using both Chrome and Safari to test, and have the same blank preview screen.

There are some errors in dev console:

<img width="1713" alt="openvscode-preview-error-1" src="https://user-images.githubusercontent.com/67305851/147178802-c8a02215-6f1e-452b-acca-4bdc18dd9610.png">

**Comment by jeanp413** [comment]
@tujeff  ah I see, the issue is you are accessing the workbench using `http` and not in localhost. As you can read in the console service workers (used by webviews in this case the markdown preview) won't work unless you use `https` or `http://localhost` (as they require a secure context https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).
So to fix your issue I'd suggest you use `https` maybe by configuring a reverse proxy (https://github.com/gitpod-io/openvscode-server/discussions/96#discussioncomment-1404354)

I'll this close for now, thanks.

**Comment by tujeff** [comment]
Yes, https did it. Thank you very much!
