### ISSUE TITLE
user data sync

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/openvscode-server#29]
We have user data sync enabled in Gitpod and can reuse it for Code Web Server. The following should be done:
- there should be gitpod-authentication extension which integrates with Gitpod Server and provides gitpod and github auth providers
  - github auth to enable extensions like GHPR: https://github.com/microsoft/vscode-pull-request-github
- product.json should be changed to gitpod user data sync endpoint and auth

**Comment by RobJamesRamos** [comment]
Don't mean to bump an old thread, but has any progress been made on this feature?

**Comment by filiptronicek** [comment]
Hi @RobJamesRamos, we have since integrated our authentication provider into the [Gitpod VS Code extension](https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-desktop) and due to API changes from Microsoft unfortunately could no longer support Settings Sync from it. Microsoft removed the `product.json` property required for third-party settings sync providers to work, and hence we will not be able to support this feature at this time.

I'm closing this as it looks like we should have updated sooner.
