### ISSUE TITLE
Release action is failing, insiders release is missing

### ISSUE THREAD

**Issue by aptalca** [gitpod-io/openvscode-server#364]
I noticed that all the insiders releases had disappeared from your repo.

I first opened a discussion entry to ask that question: https://github.com/gitpod-io/openvscode-server/discussions/363

Then I realized you use a separate repo for releases and the github action there deletes all older insiders releases before pushing a new one. However, that action for the releases is now failing. It deleted all existing insiders releases, but it has not seemed to have pushed a new release (created the tag, but not the release).

https://github.com/gitpod-io/openvscode-releases/actions/runs/2464922104

Thanks

**Comment by filiptronicek** [comment]
Hey @aptalca 👋, thanks for raising the issue! I will look into it.

**Comment by filiptronicek** [comment]
It looks like for some reason, the release was created as a draft. I published it and it is available at https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-insiders-v1.68.0.

I did not find any change of default behavior in the https://github.com/softprops/action-gh-release GitHub Action. It states, that the `draft` input gets inherited if there is an already-existing release for the tag, so maybe a previous release was marked as a draft by someone. 

I will close the issue now, since it is most likely not going to happen next time, and if it does, I think explicitly setting `draft` to `false` in [here](https://github.com/gitpod-io/openvscode-releases/blob/35550a24e8d63068913985bc03d65776b392bdc1/.github/workflows/github-release.yml#L57) will do the job.

**Comment by jeanp413** [comment]
yeah I've seen this bug when the release is created as a draft, I think it happens because of some delay in the github API after deleting the old insiders, that's why I added [this 30s delay](https://github.com/gitpod-io/openvscode-releases/blob/35550a24e8d63068913985bc03d65776b392bdc1/.github/workflows/github-release.yml#L54-L56), maybe github was a little slower than usual this time

**Comment by aptalca** [comment]
Thanks for looking into it
