### ISSUE TITLE
Project changelog or release notes

### ISSUE THREAD

**Issue by danepowell** [gitpod-io/openvscode-server#450]
Can we get a CHANGELOG or release notes attached to the GitHub releases? This is critical for contributors implementing openscode-server to know about major changes in each release.

For instance, I'm trying to determine why the `server.sh` script went missing in the 1.64.0 release, but with [over 2000 commits and 2000 files changed](https://github.com/gitpod-io/openvscode-server/compare/openvscode-server-v1.63.2...gitpod-io:openvscode-server:openvscode-server-v1.64.0) this is extremely difficult.

**Comment by danepowell** [comment]
Ah, I guess in my specific case the change came from upstream: https://github.com/microsoft/vscode/pull/140516

There's not much context in the PR but it is mentioned in the release notes: https://code.visualstudio.com/updates/v1_64#_engineering

(oddly, the 1.64.0 tag seems to be missing a dangling commit: https://github.com/gitpod-io/openvscode-server/commit/f48e724818afa83b86c5e87b7035d07a7937f8d1)

Anyway, if the answer is "follow upstream release notes" I suppose that's fine but it might be good to document somewhere.

**Comment by jeanp413** [comment]
hey @danepowell changelog is basically the same as upstream, because MS uses server internally for proprietary extensions they don't usually list them explicitly on the changelog and it would be too much work to track it ourselves.
Regarding `server.sh` it got removed in [another commit](https://github.com/gitpod-io/openvscode-server/commit/139d8c795a802e6977153f36f40f9d3e4c41f31b)
